const translations = {
    en: {
        pageTitle: "Linguamis - Languages; Easier than Ever!",
        navGrammar: "Grammar",
        navSpeaking: "Speaking",
        navReading: "Reading",
        navQuiz: "Quiz",
        navWriting: "Writing",
        navPersonas: "Personas",
        navLogin: "Log in",
        menuBtn: "Menu",
        heroTitle: "Improve your language skills. It's free!",
        heroSubtitle: "Personalized reading, speaking, and grammar exercises with actionable insights.",
        heroCta: "Sign Up For FREE!",
        cardSpeakTitle: "Speaking Coach",
        cardSpeakDesc: "Improve pronunciation with real-time AI feedback and practice exercises.",
        btnStart: "Start Speaking",
        cardListenTitle: "Listening Lab",
        cardListenDesc: "Train your ear with diverse accents, dictation tasks, and audio tests.",
        btnListen: "Start Listening",
        cardGrammarTitle: "Grammar Guide",
        cardGrammarDesc: "Master English rules with clear explanations and interactive examples.",
        btnGrammar: "Learn Grammar",
        cardWriteTitle: "Writing Studio",
        cardWriteDesc: "Enhance your writing skills for essays, emails, and creative projects.",
        btnWrite: "Start Writing",
        cardVerbsTitle: "Irregular Verbs",
        cardVerbsDesc: "Conquer tricky verbs like 'go-went-gone' with targeted practice.",
        btnVerbs: "Practice Verbs",
        cardQuizTitle: "Daily Quiz",
        cardQuizDesc: "Challenge yourself with a new quiz every day to test your knowledge.",
        btnQuiz: "Take Quiz",
        cardReadTitle: "Reading Club",
        cardReadDesc: "Explore interesting articles and stories tailored for all proficiency levels.",
        btnRead: "Start Reading",
        cardPersonasTitle: "AI Personas",
        cardPersonasDesc: "Engage in realistic conversations with diverse AI characters.",
        btnPersonas: "Meet Personas",
        footerStart: "Get Started",
        footerAbout: "About Us",
        footerHow: "How it works",
        footerStudents: "For Students",
        footerPricing: "Pricing",
        footerRes: "Resources",
        footerVocab: "Vocabulary Lists",
        footerSheets: "Worksheets",
        footerContact: "Contact Us",
        footerDesc: "Empowering English learners worldwide with adaptive technology and proven methods.",
        // --- COMING SOON NEW KEYS ---
        csPageTitle: "Linguamis - Coming Soon",
        csTitle: "Coming Soon!",
        csDesc: "We are working hard to build this feature. Check back soon for new ways to learn!",
        csBtn: "Back to Home",
        csHomeBtn: "Home"
    },
    fr: {
        pageTitle: "Linguamis - Les langues, plus facile que jamais !",
        navGrammar: "Grammaire",
        navSpeaking: "Parler",
        navReading: "Lecture",
        navQuiz: "Quiz",
        navWriting: "Écriture",
        navPersonas: "Personnas",
        navLogin: "Connexion",
        menuBtn: "Menu",
        heroTitle: "Améliorez vos compétences linguistiques. C'est gratuit !",
        heroSubtitle: "Exercices personnalisés de lecture, d'expression orale et de grammaire.",
        heroCta: "Inscrivez-vous GRATUITEMENT !",
        cardSpeakTitle: "Coach vocal",
        cardSpeakDesc: "Améliorez votre prononciation avec des retours IA en temps réel.",
        btnStart: "Commencer à parler",
        cardListenTitle: "Labo d'écoute",
        cardListenDesc: "Entraînez votre oreille avec divers accents et dictées.",
        btnListen: "Commencer l'écoute",
        cardGrammarTitle: "Guide de grammaire",
        cardGrammarDesc: "Maîtrisez les règles avec des explications claires.",
        btnGrammar: "Apprendre la grammaire",
        cardWriteTitle: "Studio d'écriture",
        cardWriteDesc: "Améliorez vos compétences rédactionnelles pour essais et emails.",
        btnWrite: "Commencer à écrire",
        cardVerbsTitle: "Verbes irréguliers",
        cardVerbsDesc: "Maîtrisez les verbes difficiles avec une pratique ciblée.",
        btnVerbs: "Pratiquer les verbes",
        cardQuizTitle: "Quiz quotidien",
        cardQuizDesc: "Testez vos connaissances avec un nouveau quiz chaque jour.",
        btnQuiz: "Faire le quiz",
        cardReadTitle: "Club de lecture",
        cardReadDesc: "Explorez des articles et histoires pour tous niveaux.",
        btnRead: "Commencer la lecture",
        cardPersonasTitle: "Personnas IA",
        cardPersonasDesc: "Engagez des conversations réalistes avec des personnages IA.",
        btnPersonas: "Rencontrer les Personnas",
        footerStart: "Commencer",
        footerAbout: "À propos",
        footerHow: "Comment ça marche",
        footerStudents: "Pour les étudiants",
        footerPricing: "Tarifs",
        footerRes: "Ressources",
        footerVocab: "Listes de vocabulaire",
        footerSheets: "Fiches d'exercices",
        footerContact: "Contactez-nous",
        footerDesc: "Autonomiser les apprenants d'anglais dans le monde entier.",
        // --- COMING SOON NEW KEYS ---
        csPageTitle: "Linguamis - Bientôt disponible",
        csTitle: "Bientôt disponible !",
        csDesc: "Nous construisons cette fonctionnalité. Revenez bientôt !",
        csBtn: "Retour à l'accueil",
        csHomeBtn: "Accueil"
    },
    es: {
        pageTitle: "Linguamis - ¡Idiomas, más fácil que nunca!",
        navGrammar: "Gramática",
        navSpeaking: "Hablar",
        navReading: "Lectura",
        navQuiz: "Cuestionario",
        navWriting: "Escritura",
        navPersonas: "Personas",
        navLogin: "Acceder",
        menuBtn: "Menú",
        heroTitle: "Mejora tus habilidades lingüísticas. ¡Es gratis!",
        heroSubtitle: "Ejercicios personalizados de lectura, habla y gramática.",
        heroCta: "¡Regístrate GRATIS!",
        cardSpeakTitle: "Entrenador de habla",
        cardSpeakDesc: "Mejora tu pronunciación con comentarios de IA en tiempo real.",
        btnStart: "Empezar a hablar",
        cardListenTitle: "Lab de escucha",
        cardListenDesc: "Entrena tu oído con diversos acentos y dictados.",
        btnListen: "Empezar a escuchar",
        cardGrammarTitle: "Guía gramatical",
        cardGrammarDesc: "Domina las reglas con explicaciones claras.",
        btnGrammar: "Aprender gramática",
        cardWriteTitle: "Estudio de escritura",
        cardWriteDesc: "Mejora tus habilidades de redacción para ensayos y correos.",
        btnWrite: "Empezar a escribir",
        cardVerbsTitle: "Verbos irregulares",
        cardVerbsDesc: "Domina los verbos difíciles con práctica específica.",
        btnVerbs: "Practicar verbos",
        cardQuizTitle: "Cuestionario diario",
        cardQuizDesc: "Ponte a prueba con un nuevo cuestionario cada día.",
        btnQuiz: "Hacer cuestionario",
        cardReadTitle: "Club de lectura",
        cardReadDesc: "Explora artículos e historias para todos los niveles.",
        btnRead: "Empezar a leer",
        cardPersonasTitle: "Personas IA",
        cardPersonasDesc: "Participa en conversaciones realistas con personajes de IA.",
        btnPersonas: "Conocer Personas",
        footerStart: "Empezar",
        footerAbout: "Sobre nosotros",
        footerHow: "Cómo funciona",
        footerStudents: "Para estudiantes",
        footerPricing: "Precios",
        footerRes: "Recursos",
        footerVocab: "Listas de vocabulario",
        footerSheets: "Hojas de trabajo",
        footerContact: "Contáctanos",
        footerDesc: "Empoderando a estudiantes de inglés en todo el mundo.",
        // --- COMING SOON NEW KEYS ---
        csPageTitle: "Linguamis - Próximamente",
        csTitle: "¡Próximamente!",
        csDesc: "Estamos construyendo esta función. ¡Vuelve pronto!",
        csBtn: "Volver al inicio",
        csHomeBtn: "Inicio"
    },
    de: {
        pageTitle: "Linguamis - Sprachen; Einfacher als je zuvor!",
        navGrammar: "Grammatik",
        navSpeaking: "Sprechen",
        navReading: "Lesen",
        navQuiz: "Quiz",
        navWriting: "Schreiben",
        navPersonas: "Personas",
        navLogin: "Einloggen",
        menuBtn: "Menü",
        heroTitle: "Verbessern Sie Ihre Sprachkenntnisse. Kostenlos!",
        heroSubtitle: "Personalisierte Lese-, Sprech- und Grammatikübungen.",
        heroCta: "KOSTENLOS anmelden!",
        cardSpeakTitle: "Sprechtrainer",
        cardSpeakDesc: "Verbessern Sie Ihre Aussprache mit Echtzeit-KI-Feedback.",
        btnStart: "Sprechen starten",
        cardListenTitle: "Hörlabor",
        cardListenDesc: "Trainieren Sie Ihr Gehör mit verschiedenen Akzenten.",
        btnListen: "Hören starten",
        cardGrammarTitle: "Grammatikführer",
        cardGrammarDesc: "Meistern Sie Regeln mit klaren Erklärungen.",
        btnGrammar: "Grammatik lernen",
        cardWriteTitle: "Schreibstudio",
        cardWriteDesc: "Verbessern Sie Ihre Schreibfähigkeiten für Aufsätze und E-Mails.",
        btnWrite: "Schreiben starten",
        cardVerbsTitle: "Unregelmäßige Verben",
        cardVerbsDesc: "Meistern Sie schwierige Verben mit gezielten Übungen.",
        btnVerbs: "Verben üben",
        cardQuizTitle: "Tägliches Quiz",
        cardQuizDesc: "Testen Sie Ihr Wissen täglich mit einem neuen Quiz.",
        btnQuiz: "Quiz starten",
        cardReadTitle: "Leseclub",
        cardReadDesc: "Entdecken Sie Artikel und Geschichten für alle Niveaus.",
        btnRead: "Lesen starten",
        cardPersonasTitle: "KI-Personas",
        cardPersonasDesc: "Führen Sie realistische Gespräche mit KI-Charakteren.",
        btnPersonas: "Personas treffen",
        footerStart: "Loslegen",
        footerAbout: "Über uns",
        footerHow: "Wie es funktioniert",
        footerStudents: "Für Schüler",
        footerPricing: "Preise",
        footerRes: "Ressourcen",
        footerVocab: "Vokabellisten",
        footerSheets: "Arbeitsblätter",
        footerContact: "Kontakt",
        footerDesc: "Englischlerne weltweit mit adaptiver Technologie stärken.",
        // --- COMING SOON NEW KEYS ---
        csPageTitle: "Linguamis - Demnächst",
        csTitle: "Demnächst!",
        csDesc: "Wir arbeiten an dieser Funktion. Bis bald!",
        csBtn: "Zurück zur Startseite",
        csHomeBtn: "Startseite"
    },
    tr: {
        pageTitle: "Linguamis - Diller; Hiç Olmadığı Kadar Kolay!",
        navGrammar: "Dilbilgisi",
        navSpeaking: "Konuşma",
        navReading: "Okuma",
        navQuiz: "Test",
        navWriting: "Yazma",
        navPersonas: "Personalar",
        navLogin: "Giriş Yap",
        menuBtn: "Menü",
        heroTitle: "Dil becerilerinizi geliştirin. Tamamen ücretsiz!",
        heroSubtitle: "Kişiselleştirilmiş okuma, konuşma ve dilbilgisi alıştırmaları.",
        heroCta: "ÜCRETSİZ Kaydol!",
        cardSpeakTitle: "Konuşma Koçu",
        cardSpeakDesc: "Gerçek zamanlı yapay zeka geri bildirimi ile telaffuzunuzu geliştirin.",
        btnStart: "Konuşmaya Başla",
        cardListenTitle: "Dinleme Laboratuvarı",
        cardListenDesc: "Farklı aksanlar ve dikte görevleri ile kulağınızı eğitin.",
        btnListen: "Dinlemeye Başla",
        cardGrammarTitle: "Dilbilgisi Rehberi",
        cardGrammarDesc: "Net açıklamalar ve etkileşimli örneklerle kuralları öğrenin.",
        btnGrammar: "Dilbilgisi Öğren",
        cardWriteTitle: "Yazma Stüdyosu",
        cardWriteDesc: "Kompozisyonlar ve e-postalar için yazma becerilerinizi geliştirin.",
        btnWrite: "Yazmaya Başla",
        cardVerbsTitle: "Düzensiz Fiiller",
        cardVerbsDesc: "Zorlu fiilleri hedefe yönelik alıştırmalarla fethedin.",
        btnVerbs: "Fiil Çalış",
        cardQuizTitle: "Günlük Test",
        cardQuizDesc: "Her gün yeni bir test ile bilginizi sınayın.",
        btnQuiz: "Testi Çöz",
        cardReadTitle: "Okuma Kulübü",
        cardReadDesc: "Her seviyeye uygun ilginç makaleler ve hikayeler keşfedin.",
        btnRead: "Okumaya Başla",
        cardPersonasTitle: "YZ Personaları",
        cardPersonasDesc: "Farklı YZ karakterleriyle gerçekçi sohbetlere katılın.",
        btnPersonas: "Personalarla Tanış",
        footerStart: "Başlayın",
        footerAbout: "Hakkımızda",
        footerHow: "Nasıl çalışır",
        footerStudents: "Öğrenciler İçin",
        footerPricing: "Fiyatlandırma",
        footerRes: "Kaynaklar",
        footerVocab: "Kelime Listeleri",
        footerSheets: "Çalışma Kağıtları",
        footerContact: "İletişim",
        footerDesc: "Dünya çapındaki İngilizce öğrencilerini adaptif teknoloji ile güçlendiriyoruz.",
        // --- COMING SOON NEW KEYS ---
        csPageTitle: "Linguamis - Çok Yakında",
        csTitle: "Çok Yakında!",
        csDesc: "Bu özellik üzerinde çalışıyoruz. Yakında tekrar kontrol edin!",
        csBtn: "Ana Sayfaya Dön",
        csHomeBtn: "Ana Sayfa"
    },
    ru: {
        pageTitle: "Linguamis - Языки; Проще, чем когда-либо!",
        navGrammar: "Грамматика",
        navSpeaking: "Разговор",
        navReading: "Чтение",
        navQuiz: "Викторина",
        navWriting: "Письмо",
        navPersonas: "Персоны",
        navLogin: "Войти",
        menuBtn: "Меню",
        heroTitle: "Улучшите свои языковые навыки. Это бесплатно!",
        heroSubtitle: "Персонализированные упражнения по чтению, речи и грамматике.",
        heroCta: "Зарегистрируйтесь БЕСПЛАТНО!",
        cardSpeakTitle: "Тренер по речи",
        cardSpeakDesc: "Улучшите произношение с помощью ИИ в реальном времени.",
        btnStart: "Начать говорить",
        cardListenTitle: "Лаборатория слуха",
        cardListenDesc: "Тренируйте слух с помощью различных акцентов и диктантов.",
        btnListen: "Начать слушать",
        cardGrammarTitle: "Гид по грамматике",
        cardGrammarDesc: "Освойте правила с понятными объяснениями.",
        btnGrammar: "Учить грамматику",
        cardWriteTitle: "Студия письма",
        cardWriteDesc: "Улучшите навыки письма для эссе и писем.",
        btnWrite: "Начать писать",
        cardVerbsTitle: "Неправильные глаголы",
        cardVerbsDesc: "Освойте сложные глаголы с помощью упражнений.",
        btnVerbs: "Тренировать глаголы",
        cardQuizTitle: "Ежедневный тест",
        cardQuizDesc: "Проверяйте свои знания с новым тестом каждый день.",
        btnQuiz: "Пройти тест",
        cardReadTitle: "Клуб чтения",
        cardReadDesc: "Изучайте интересные статьи и истории для всех уровней.",
        btnRead: "Начать читать",
        cardPersonasTitle: "ИИ Персоны",
        cardPersonasDesc: "Участвуйте в реалистичных беседах с ИИ персонажами.",
        btnPersonas: "Встретить Персон",
        footerStart: "Начать",
        footerAbout: "О нас",
        footerHow: "Как это работает",
        footerStudents: "Для студентов",
        footerPricing: "Цены",
        footerRes: "Ресурсы",
        footerVocab: "Списки слов",
        footerSheets: "Рабочие листы",
        footerContact: "Контакты",
        footerDesc: "Расширение возможностей изучающих английский язык по всему миру.",
        // --- COMING SOON NEW KEYS ---
        csPageTitle: "Linguamis - Скоро",
        csTitle: "Скоро!",
        csDesc: "Мы работаем над этой функцией. Заходите позже!",
        csBtn: "На главную",
        csHomeBtn: "Главная"
    },
    ar: {
        pageTitle: "Linguamis - اللغات؛ أسهل من أي وقت مضى!",
        navGrammar: "القواعد",
        navSpeaking: "المحادثة",
        navReading: "القراءة",
        navQuiz: "اختبار",
        navWriting: "الكتابة",
        navPersonas: "شخصيات",
        navLogin: "دخول",
        menuBtn: "قائمة",
        heroTitle: "حسن مهاراتك اللغوية. مجاناً!",
        heroSubtitle: "تمارين قراءة ومحادثة وقواعد مخصصة مع رؤى قابلة للتطبيق.",
        heroCta: "سجل مجاناً الآن!",
        cardSpeakTitle: "مدرب المحادثة",
        cardSpeakDesc: "حسن نطقك مع تغذية راجعة فورية من الذكاء الاصطناعي.",
        btnStart: "ابدأ المحادثة",
        cardListenTitle: "مختبر الاستماع",
        cardListenDesc: "درب أذنك على لهجات متنوعة ومهام الإملاء.",
        btnListen: "ابدأ الاستماع",
        cardGrammarTitle: "دليل القواعد",
        cardGrammarDesc: "أتقن القواعد مع شروحات واضحة وأمثلة تفاعلية.",
        btnGrammar: "تعلم القواعد",
        cardWriteTitle: "استوديو الكتابة",
        cardWriteDesc: "عزز مهاراتك في الكتابة للمقالات ورسائل البريد الإلكتروني.",
        btnWrite: "ابدأ الكتابة",
        cardVerbsTitle: "الأفعال الشاذة",
        cardVerbsDesc: "تغلب على الأفعال الصعبة من خلال ممارسة مستهدفة.",
        btnVerbs: "تدرب على الأفعال",
        cardQuizTitle: "الاختبار اليومي",
        cardQuizDesc: "تحدى نفسك باختبار جديد كل يوم لاختبار معرفتك.",
        btnQuiz: "ابدأ الاختبار",
        cardReadTitle: "نادي القراءة",
        cardReadDesc: "استكشف مقالات وقصص مثيرة تناسب جميع المستويات.",
        btnRead: "ابدأ القراءة",
        cardPersonasTitle: "شخصيات الذكاء الاصطناعي",
        cardPersonasDesc: "شارك في محادثات واقعية مع شخصيات ذكية متنوعة.",
        btnPersonas: "قابل الشخصيات",
        footerStart: "ابدأ",
        footerAbout: "من نحن",
        footerHow: "كيف يعمل",
        footerStudents: "للطلاب",
        footerPricing: "الأسعار",
        footerRes: "الموارد",
        footerVocab: "قوائم المفردات",
        footerSheets: "أوراق عمل",
        footerContact: "اتصل بنا",
        footerDesc: "تمكين متعلمي اللغة الإنجليزية حول العالم بتقنيات تكيفية.",
        // --- COMING SOON NEW KEYS ---
        csPageTitle: "Linguamis - قريباً",
        csTitle: "قريباً!",
        csDesc: "نحن نعمل على هذه الميزة. تحقق مرة أخرى قريباً!",
        csBtn: "العودة للرئيسية",
        csHomeBtn: "الرئيسية"
    }
};

function changeLanguage(lang) {
    // 1. Set correct text direction (RTL for Arabic)
    if (lang === 'ar') {
        document.documentElement.setAttribute('dir', 'rtl');
        document.documentElement.setAttribute('lang', 'ar');
    } else {
        document.documentElement.setAttribute('dir', 'ltr');
        document.documentElement.setAttribute('lang', lang);
    }

    // 2. Find all elements with 'data-i18n' and update text
    const elements = document.querySelectorAll('[data-i18n]');
    
    elements.forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });

    // 3. Sync both dropdowns (Mobile and Desktop)
    const mainSelect = document.getElementById('languageSelect');
    if (mainSelect) mainSelect.value = lang;
    
    const mobileSelect = document.getElementById('mobileLangSelect');
    if (mobileSelect) mobileSelect.value = lang;
    
    // 4. Save preference to LocalStorage
    localStorage.setItem('selectedLanguage', lang);
}

// Load saved language on page start
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'en';
    changeLanguage(savedLang);
});
