/* --- lang.js (With Auto-Reload) --- */

const translations = {
    en: {
        pageTitle: "Linguamis - Languages; Easier than Ever!",
        navGrammar: "Grammar",
        navSpeaking: "Speaking",
        navReading: "Reading",
        navQuiz: "Quiz",
        navWriting: "Writing",
        navPersonas: "Personas",
        navLogin: "Log in",
        menuBtn: "Menu",
        heroTitle: "Improve your language skills. It's free!",
        heroSubtitle: "Personalized reading, speaking, and grammar exercises with actionable insights.",
        heroCta: "Sign Up For FREE!",
        cardSpeakTitle: "Speaking Coach",
        cardSpeakDesc: "Improve pronunciation with real-time AI feedback and practice exercises.",
        btnStart: "Start Speaking",
        cardListenTitle: "Listening Lab",
        cardListenDesc: "Train your ear with diverse accents, dictation tasks, and audio tests.",
        btnListen: "Start Listening",
        cardGrammarTitle: "Grammar Guide",
        cardGrammarDesc: "Master English rules with clear explanations and interactive examples.",
        btnGrammar: "Learn Grammar",
        cardWriteTitle: "Writing Studio",
        cardWriteDesc: "Enhance your writing skills for essays, emails, and creative projects.",
        btnWrite: "Start Writing",
        cardVerbsTitle: "Irregular Verbs",
        cardVerbsDesc: "Conquer tricky verbs like 'go-went-gone' with targeted practice.",
        btnVerbs: "Practice Verbs",
        cardQuizTitle: "Daily Quiz",
        cardQuizDesc: "Challenge yourself with a new quiz every day to test your knowledge.",
        btnQuiz: "Take Quiz",
        cardReadTitle: "Reading Club",
        cardReadDesc: "Explore interesting articles and stories tailored for all proficiency levels.",
        btnRead: "Start Reading",
        cardPersonasTitle: "AI Personas",
        cardPersonasDesc: "Engage in realistic conversations with diverse AI characters.",
        btnPersonas: "Meet Personas",
        // NEW GAMES SECTION
        cardGamesTitle: "Interactive Games",
        cardGamesDesc: "Boost your skills with fun puzzles, word matching, and challenges.",
        btnGames: "Play Games",
        // END NEW GAMES SECTION
        footerStart: "Get Started",
        footerAbout: "About Us",
        footerHow: "How it works",
        footerStudents: "For Students",
        footerPricing: "Pricing",
        footerRes: "Resources",
        footerVocab: "Vocabulary Lists",
        footerSheets: "Worksheets",
        footerContact: "Contact Us",
        footerDesc: "Empowering English learners worldwide with adaptive technology and proven methods.",
        csPageTitle: "Linguamis - Coming Soon",
        csTitle: "Coming Soon!",
        csDesc: "We are working hard to build this feature. Check back soon for new ways to learn!",
        csBtn: "Back to Home",
        csHomeBtn: "Home"
    },
    fr: {
        pageTitle: "Linguamis - Les langues, plus facile que jamais !",
        navGrammar: "Grammaire",
        navSpeaking: "Parler",
        navReading: "Lecture",
        navQuiz: "Quiz",
        navWriting: "Écriture",
        navPersonas: "Personnas",
        navLogin: "Connexion",
        menuBtn: "Menu",
        heroTitle: "Améliorez vos compétences linguistiques. C'est gratuit !",
        heroSubtitle: "Exercices personnalisés de lecture, d'expression orale et de grammaire.",
        heroCta: "Inscrivez-vous GRATUITEMENT !",
        cardSpeakTitle: "Coach vocal",
        cardSpeakDesc: "Améliorez votre prononciation avec des retours IA en temps réel.",
        btnStart: "Commencer à parler",
        cardListenTitle: "Labo d'écoute",
        cardListenDesc: "Entraînez votre oreille avec divers accents et dictées.",
        btnListen: "Commencer l'écoute",
        cardGrammarTitle: "Guide de grammaire",
        cardGrammarDesc: "Maîtrisez les règles avec des explications claires.",
        btnGrammar: "Apprendre la grammaire",
        cardWriteTitle: "Studio d'écriture",
        cardWriteDesc: "Améliorez vos compétences rédactionnelles pour essais et emails.",
        btnWrite: "Commencer à écrire",
        cardVerbsTitle: "Verbes irréguliers",
        cardVerbsDesc: "Maîtrisez les verbes difficiles avec une pratique ciblée.",
        btnVerbs: "Pratiquer les verbes",
        cardQuizTitle: "Quiz quotidien",
        cardQuizDesc: "Testez vos connaissances avec un nouveau quiz chaque jour.",
        btnQuiz: "Faire le quiz",
        cardReadTitle: "Club de lecture",
        cardReadDesc: "Explorez des articles et histoires pour tous niveaux.",
        btnRead: "Commencer la lecture",
        cardPersonasTitle: "Personnas IA",
        cardPersonasDesc: "Engagez des conversations réalistes avec des personnages IA.",
        btnPersonas: "Rencontrer les Personnas",
        // NEW GAMES SECTION
        cardGamesTitle: "Jeux Interactifs",
        cardGamesDesc: "Améliorez vos compétences avec des puzzles et des défis amusants.",
        btnGames: "Jouer",
        // END NEW GAMES SECTION
        footerStart: "Commencer",
        footerAbout: "À propos",
        footerHow: "Comment ça marche",
        footerStudents: "Pour les étudiants",
        footerPricing: "Tarifs",
        footerRes: "Ressources",
        footerVocab: "Listes de vocabulaire",
        footerSheets: "Fiches d'exercices",
        footerContact: "Contactez-nous",
        footerDesc: "Autonomiser les apprenants d'anglais dans le monde entier.",
        csPageTitle: "Linguamis - Bientôt disponible",
        csTitle: "Bientôt disponible !",
        csDesc: "Nous construisons cette fonctionnalité. Revenez bientôt !",
        csBtn: "Retour à l'accueil",
        csHomeBtn: "Accueil"
    },
    es: {
        pageTitle: "Linguamis - ¡Idiomas, más fácil que nunca!",
        navGrammar: "Gramática",
        navSpeaking: "Hablar",
        navReading: "Lectura",
        navQuiz: "Cuestionario",
        navWriting: "Escritura",
        navPersonas: "Personas",
        navLogin: "Acceder",
        menuBtn: "Menú",
        heroTitle: "Mejora tus habilidades lingüísticas. ¡Es gratis!",
        heroSubtitle: "Ejercicios personalizados de lectura, habla y gramática.",
        heroCta: "¡Regístrate GRATIS!",
        cardSpeakTitle: "Entrenador de habla",
        cardSpeakDesc: "Mejora tu pronunciación con comentarios de IA en tiempo real.",
        btnStart: "Empezar a hablar",
        cardListenTitle: "Lab de escucha",
        cardListenDesc: "Entrena tu oído con diversos acentos y dictados.",
        btnListen: "Empezar a escuchar",
        cardGrammarTitle: "Guía gramatical",
        cardGrammarDesc: "Domina las reglas con explicaciones claras.",
        btnGrammar: "Aprender gramática",
        cardWriteTitle: "Estudio de escritura",
        cardWriteDesc: "Mejora tus habilidades de redacción para ensayos y correos.",
        btnWrite: "Empezar a escribir",
        cardVerbsTitle: "Verbos irregulares",
        cardVerbsDesc: "Domina los verbos difíciles con práctica específica.",
        btnVerbs: "Practicar verbos",
        cardQuizTitle: "Cuestionario diario",
        cardQuizDesc: "Ponte a prueba con un nuevo cuestionario cada día.",
        btnQuiz: "Hacer cuestionario",
        cardReadTitle: "Club de lectura",
        cardReadDesc: "Explora artículos e historias para todos los niveles.",
        btnRead: "Empezar a leer",
        cardPersonasTitle: "Personas IA",
        cardPersonasDesc: "Participa en conversaciones realistas con personajes de IA.",
        btnPersonas: "Conocer Personas",
        // NEW GAMES SECTION
        cardGamesTitle: "Juegos Interactivos",
        cardGamesDesc: "Mejora tus habilidades con rompecabezas y desafíos divertidos.",
        btnGames: "Jugar",
        // END NEW GAMES SECTION
        footerStart: "Empezar",
        footerAbout: "Sobre nosotros",
        footerHow: "Cómo funciona",
        footerStudents: "Para estudiantes",
        footerPricing: "Precios",
        footerRes: "Recursos",
        footerVocab: "Listas de vocabulario",
        footerSheets: "Hojas de trabajo",
        footerContact: "Contáctanos",
        footerDesc: "Empoderando a estudiantes de inglés en todo el mundo.",
        csPageTitle: "Linguamis - Próximamente",
        csTitle: "¡Próximamente!",
        csDesc: "Estamos construyendo esta función. ¡Vuelve pronto!",
        csBtn: "Volver al inicio",
        csHomeBtn: "Inicio"
    },
    de: {
        pageTitle: "Linguamis - Sprachen; Einfacher als je zuvor!",
        navGrammar: "Grammatik",
        navSpeaking: "Sprechen",
        navReading: "Lesen",
        navQuiz: "Quiz",
        navWriting: "Schreiben",
        navPersonas: "Personas",
        navLogin: "Einloggen",
        menuBtn: "Menü",
        heroTitle: "Verbessern Sie Ihre Sprachkenntnisse. Kostenlos!",
        heroSubtitle: "Personalisierte Lese-, Sprech- und Grammatikübungen.",
        heroCta: "KOSTENLOS anmelden!",
        cardSpeakTitle: "Sprechtrainer",
        cardSpeakDesc: "Verbessern Sie Ihre Aussprache mit Echtzeit-KI-Feedback.",
        btnStart: "Sprechen starten",
        cardListenTitle: "Hörlabor",
        cardListenDesc: "Trainieren Sie Ihr Gehör mit verschiedenen Akzenten.",
        btnListen: "Hören starten",
        cardGrammarTitle: "Grammatikführer",
        cardGrammarDesc: "Meistern Sie Regeln mit klaren Erklärungen.",
        btnGrammar: "Grammatik lernen",
        cardWriteTitle: "Schreibstudio",
        cardWriteDesc: "Verbessern Sie Ihre Schreibfähigkeiten für Aufsätze und E-Mails.",
        btnWrite: "Schreiben starten",
        cardVerbsTitle: "Unregelmäßige Verben",
        cardVerbsDesc: "Meistern Sie schwierige Verben mit gezielten Übungen.",
        btnVerbs: "Verben üben",
        cardQuizTitle: "Tägliches Quiz",
        cardQuizDesc: "Testen Sie Ihr Wissen täglich mit einem neuen Quiz.",
        btnQuiz: "Quiz starten",
        cardReadTitle: "Leseclub",
        cardReadDesc: "Entdecken Sie Artikel und Geschichten für alle Niveaus.",
        btnRead: "Lesen starten",
        cardPersonasTitle: "KI-Personas",
        cardPersonasDesc: "Führen Sie realistische Gespräche mit KI-Charakteren.",
        btnPersonas: "Personas treffen",
        // NEW GAMES SECTION
        cardGamesTitle: "Interaktive Spiele",
        cardGamesDesc: "Verbessern Sie Ihre Fähigkeiten mit lustigen Rätseln.",
        btnGames: "Spiele spielen",
        // END NEW GAMES SECTION
        footerStart: "Loslegen",
        footerAbout: "Über uns",
        footerHow: "Wie es funktioniert",
        footerStudents: "Für Schüler",
        footerPricing: "Preise",
        footerRes: "Ressourcen",
        footerVocab: "Vokabellisten",
        footerSheets: "Arbeitsblätter",
        footerContact: "Kontakt",
        footerDesc: "Englischlerne weltweit mit adaptiver Technologie stärken.",
        csPageTitle: "Linguamis - Demnächst",
        csTitle: "Demnächst!",
        csDesc: "Wir arbeiten an dieser Funktion. Bis bald!",
        csBtn: "Zurück zur Startseite",
        csHomeBtn: "Startseite"
    },
    tr: {
        pageTitle: "Linguamis - Diller; Hiç Olmadığı Kadar Kolay!",
        navGrammar: "Dilbilgisi",
        navSpeaking: "Konuşma",
        navReading: "Okuma",
        navQuiz: "Test",
        navWriting: "Yazma",
        navPersonas: "Personalar",
        navLogin: "Giriş Yap",
        menuBtn: "Menü",
        heroTitle: "Dil becerilerinizi geliştirin. Tamamen ücretsiz!",
        heroSubtitle: "Kişiselleştirilmiş okuma, konuşma ve dilbilgisi alıştırmaları.",
        heroCta: "ÜCRETSİZ Kaydol!",
        cardSpeakTitle: "Konuşma Koçu",
        cardSpeakDesc: "Gerçek zamanlı yapay zeka geri bildirimi ile telaffuzunuzu geliştirin.",
        btnStart: "Konuşmaya Başla",
        cardListenTitle: "Dinleme Laboratuvarı",
        cardListenDesc: "Farklı aksanlar ve dikte görevleri ile kulağınızı eğitin.",
        btnListen: "Dinlemeye Başla",
        cardGrammarTitle: "Dilbilgisi Rehberi",
        cardGrammarDesc: "Net açıklamalar ve etkileşimli örneklerle kuralları öğrenin.",
        btnGrammar: "Dilbilgisi Öğren",
        cardWriteTitle: "Yazma Stüdyosu",
        cardWriteDesc: "Kompozisyonlar ve e-postalar için yazma becerilerinizi geliştirin.",
        btnWrite: "Yazmaya Başla",
        cardVerbsTitle: "Düzensiz Fiiller",
        cardVerbsDesc: "Zorlu fiilleri hedefe yönelik alıştırmalarla fethedin.",
        btnVerbs: "Fiil Çalış",
        cardQuizTitle: "Günlük Test",
        cardQuizDesc: "Her gün yeni bir test ile bilginizi sınayın.",
        btnQuiz: "Testi Çöz",
        cardReadTitle: "Okuma Kulübü",
        cardReadDesc: "Her seviyeye uygun ilginç makaleler ve hikayeler keşfedin.",
        btnRead: "Okumaya Başla",
        cardPersonasTitle: "YZ Personaları",
        cardPersonasDesc: "Farklı YZ karakterleriyle gerçekçi sohbetlere katılın.",
        btnPersonas: "Personalarla Tanış",
        // NEW GAMES SECTION
        cardGamesTitle: "İnteraktif Oyunlar",
        cardGamesDesc: "Eğlenceli bulmacalar ve meydan okumalarla becerilerinizi geliştirin.",
        btnGames: "Oyun Oyna",
        // END NEW GAMES SECTION
        footerStart: "Başlayın",
        footerAbout: "Hakkımızda",
        footerHow: "Nasıl çalışır",
        footerStudents: "Öğrenciler İçin",
        footerPricing: "Fiyatlandırma",
        footerRes: "Kaynaklar",
        footerVocab: "Kelime Listeleri",
        footerSheets: "Çalışma Kağıtları",
        footerContact: "İletişim",
        footerDesc: "Dünya çapındaki İngilizce öğrencilerini adaptif teknoloji ile güçlendiriyoruz.",
        csPageTitle: "Linguamis - Çok Yakında",
        csTitle: "Çok Yakında!",
        csDesc: "Bu özellik üzerinde çalışıyoruz. Yakında tekrar kontrol edin!",
        csBtn: "Ana Sayfaya Dön",
        csHomeBtn: "Ana Sayfa"
    },
    ru: {
        pageTitle: "Linguamis - Языки; Проще, чем когда-либо!",
        navGrammar: "Грамматика",
        navSpeaking: "Разговор",
        navReading: "Чтение",
        navQuiz: "Викторина",
        navWriting: "Письмо",
        navPersonas: "Персоны",
        navLogin: "Войти",
        menuBtn: "Меню",
        heroTitle: "Улучшите свои языковые навыки. Это бесплатно!",
        heroSubtitle: "Персонализированные упражнения по чтению, речи и грамматике.",
        heroCta: "Зарегистрируйтесь БЕСПЛАТНО!",
        cardSpeakTitle: "Тренер по речи",
        cardSpeakDesc: "Улучшите произношение с помощью ИИ в реальном времени.",
        btnStart: "Начать говорить",
        cardListenTitle: "Лаборатория слуха",
        cardListenDesc: "Тренируйте слух с помощью различных акцентов и диктантов.",
        btnListen: "Начать слушать",
        cardGrammarTitle: "Гид по грамматике",
        cardGrammarDesc: "Освойте правила с понятными объяснениями.",
        btnGrammar: "Учить грамматику",
        cardWriteTitle: "Студия письма",
        cardWriteDesc: "Улучшите навыки письма для эссе и писем.",
        btnWrite: "Начать писать",
        cardVerbsTitle: "Неправильные глаголы",
        cardVerbsDesc: "Освойте сложные глаголы с помощью упражнений.",
        btnVerbs: "Тренировать глаголы",
        cardQuizTitle: "Ежедневный тест",
        cardQuizDesc: "Проверяйте свои знания с новым тестом каждый день.",
        btnQuiz: "Пройти тест",
        cardReadTitle: "Клуб чтения",
        cardReadDesc: "Изучайте интересные статьи и истории для всех уровней.",
        btnRead: "Начать читать",
        cardPersonasTitle: "ИИ Персоны",
        cardPersonasDesc: "Участвуйте в реалистичных беседах с ИИ персонажами.",
        btnPersonas: "Встретить Персон",
        // NEW GAMES SECTION
        cardGamesTitle: "Интерактивные игры",
        cardGamesDesc: "Улучшайте навыки с помощью веселых головоломок и задач.",
        btnGames: "Играть",
        // END NEW GAMES SECTION
        footerStart: "Начать",
        footerAbout: "О нас",
        footerHow: "Как это работает",
        footerStudents: "Для студентов",
        footerPricing: "Цены",
        footerRes: "Ресурсы",
        footerVocab: "Списки слов",
        footerSheets: "Рабочие листы",
        footerContact: "Контакты",
        footerDesc: "Расширение возможностей изучающих английский язык по всему миру.",
        csPageTitle: "Linguamis - Скоро",
        csTitle: "Скоро!",
        csDesc: "Мы работаем над этой функцией. Заходите позже!",
        csBtn: "На главную",
        csHomeBtn: "Главная"
    },
    ar: {
        pageTitle: "Linguamis - اللغات؛ أسهل من أي وقت مضى!",
        navGrammar: "القواعد",
        navSpeaking: "المحادثة",
        navReading: "القراءة",
        navQuiz: "اختبار",
        navWriting: "الكتابة",
        navPersonas: "شخصيات",
        navLogin: "دخول",
        menuBtn: "قائمة",
        heroTitle: "حسن مهاراتك اللغوية. مجاناً!",
        heroSubtitle: "تمارين قراءة ومحادثة وقواعد مخصصة مع رؤى قابلة للتطبيق.",
        heroCta: "سجل مجاناً الآن!",
        cardSpeakTitle: "مدرب المحادثة",
        cardSpeakDesc: "حسن نطقك مع تغذية راجعة فورية من الذكاء الاصطناعي.",
        btnStart: "ابدأ المحادثة",
        cardListenTitle: "مختبر الاستماع",
        cardListenDesc: "درب أذنك على لهجات متنوعة ومهام الإملاء.",
        btnListen: "ابدأ الاستماع",
        cardGrammarTitle: "دليل القواعد",
        cardGrammarDesc: "أتقن القواعد مع شروحات واضحة وأمثلة تفاعلية.",
        btnGrammar: "تعلم القواعد",
        cardWriteTitle: "استوديو الكتابة",
        cardWriteDesc: "عزز مهاراتك في الكتابة للمقالات ورسائل البريد الإلكتروني.",
        btnWrite: "ابدأ الكتابة",
        cardVerbsTitle: "الأفعال الشاذة",
        cardVerbsDesc: "تغلب على الأفعال الصعبة من خلال ممارسة مستهدفة.",
        btnVerbs: "تدرب على الأفعال",
        cardQuizTitle: "الاختبار اليومي",
        cardQuizDesc: "تحدى نفسك باختبار جديد كل يوم لاختبار معرفتك.",
        btnQuiz: "ابدأ الاختبار",
        cardReadTitle: "نادي القراءة",
        cardReadDesc: "استكشف مقالات وقصص مثيرة تناسب جميع المستويات.",
        btnRead: "ابدأ القراءة",
        cardPersonasTitle: "شخصيات الذكاء الاصطناعي",
        cardPersonasDesc: "شارك في محادثات واقعية مع شخصيات ذكية متنوعة.",
        btnPersonas: "قابل الشخصيات",
        // NEW GAMES SECTION
        cardGamesTitle: "ألعاب تفاعلية",
        cardGamesDesc: "عزز مهاراتك بالألغاز والتحديات الممتعة.",
        btnGames: "العب الآن",
        // END NEW GAMES SECTION
        footerStart: "ابدأ",
        footerAbout: "من نحن",
        footerHow: "كيف يعمل",
        footerStudents: "للطلاب",
        footerPricing: "الأسعار",
        footerRes: "الموارد",
        footerVocab: "قوائم المفردات",
        footerSheets: "أوراق عمل",
        footerContact: "اتصل بنا",
        footerDesc: "تمكين متعلمي اللغة الإنجليزية حول العالم بتقنيات تكيفية.",
        csPageTitle: "Linguamis - قريباً",
        csTitle: "قريباً!",
        csDesc: "نحن نعمل على هذه الميزة. تحقق مرة أخرى قريباً!",
        csBtn: "العودة للرئيسية",
        csHomeBtn: "الرئيسية"
    },
    it: {
        pageTitle: "Linguamis - Lingue; Più facile che mai!",
        navGrammar: "Grammatica",
        navSpeaking: "Parlare",
        navReading: "Lettura",
        navQuiz: "Quiz",
        navWriting: "Scrittura",
        navPersonas: "Persona",
        navLogin: "Accedi",
        menuBtn: "Menu",
        heroTitle: "Migliora le tue abilità linguistiche. È gratis!",
        heroSubtitle: "Esercizi personalizzati di lettura, conversazione e grammatica.",
        heroCta: "Iscriviti GRATIS!",
        cardSpeakTitle: "Coach Vocale",
        cardSpeakDesc: "Migliora la pronuncia con il feedback dell'IA in tempo reale.",
        btnStart: "Inizia a Parlare",
        cardListenTitle: "Lab Ascolto",
        cardListenDesc: "Allena il tuo orecchio con accenti diversi e dettati.",
        btnListen: "Inizia ad Ascoltare",
        cardGrammarTitle: "Guida Grammaticale",
        cardGrammarDesc: "Padroneggia le regole con spiegazioni chiare.",
        btnGrammar: "Impara Grammatica",
        cardWriteTitle: "Studio Scrittura",
        cardWriteDesc: "Migliora le tue abilità di scrittura per saggi ed email.",
        btnWrite: "Inizia a Scrivere",
        cardVerbsTitle: "Verbi Irregolari",
        cardVerbsDesc: "Conquista i verbi difficili con esercizi mirati.",
        btnVerbs: "Pratica Verbi",
        cardQuizTitle: "Quiz Giornaliero",
        cardQuizDesc: "Mettiti alla prova con un nuovo quiz ogni giorno.",
        btnQuiz: "Fai il Quiz",
        cardReadTitle: "Club del Libro",
        cardReadDesc: "Esplora articoli e storie per tutti i livelli.",
        btnRead: "Inizia a Leggere",
        cardPersonasTitle: "Persona IA",
        cardPersonasDesc: "Partecipa a conversazioni realistiche con personaggi IA.",
        btnPersonas: "Incontra Persona",
        // NEW GAMES SECTION
        cardGamesTitle: "Giochi Interattivi",
        cardGamesDesc: "Migliora le tue abilità con puzzle e sfide divertenti.",
        btnGames: "Gioca",
        // END NEW GAMES SECTION
        footerStart: "Iniziare",
        footerAbout: "Chi Siamo",
        footerHow: "Come Funziona",
        footerStudents: "Per Studenti",
        footerPricing: "Prezzi",
        footerRes: "Risorse",
        footerVocab: "Vocabolario",
        footerSheets: "Esercizi",
        footerContact: "Contatti",
        footerDesc: "Potenziare gli studenti di inglese in tutto il mondo.",
    },
    zh: {
        pageTitle: "Linguamis - 语言；比以往更简单！",
        navGrammar: "语法",
        navSpeaking: "口语",
        navReading: "阅读",
        navQuiz: "测验",
        navWriting: "写作",
        navPersonas: "角色",
        navLogin: "登录",
        menuBtn: "菜单",
        heroTitle: "提高你的语言技能。它是免费的！",
        heroSubtitle: "个性化的阅读、口语和语法练习。",
        heroCta: "免费注册！",
        cardSpeakTitle: "口语教练",
        cardSpeakDesc: "通过实时 AI 反馈改善发音。",
        btnStart: "开始说",
        cardListenTitle: "听力实验室",
        cardListenDesc: "用不同的口音和听写任务训练你的耳朵。",
        btnListen: "开始听",
        cardGrammarTitle: "语法指南",
        cardGrammarDesc: "通过清晰的解释掌握规则。",
        btnGrammar: "学习语法",
        cardWriteTitle: "写作工作室",
        cardWriteDesc: "提高你的论文和电子邮件写作技巧。",
        btnWrite: "开始写",
        cardVerbsTitle: "不规则动词",
        cardVerbsDesc: "通过针对性练习攻克生僻动词。",
        btnVerbs: "练习动词",
        cardQuizTitle: "每日测验",
        cardQuizDesc: "每天用新测验挑战自己。",
        btnQuiz: "参加测验",
        cardReadTitle: "读书俱乐部",
        cardReadDesc: "探索适合所有水平的有趣文章和故事。",
        btnRead: "开始阅读",
        cardPersonasTitle: "AI 角色",
        cardPersonasDesc: "与不同的 AI 角色进行现实对话。",
        btnPersonas: "遇见角色",
        // NEW GAMES SECTION
        cardGamesTitle: "互动游戏",
        cardGamesDesc: "通过有趣的拼图和挑战提高你的技能。",
        btnGames: "玩游戏",
        // END NEW GAMES SECTION
        footerStart: "开始",
        footerAbout: "关于我们",
        footerHow: "工作原理",
        footerStudents: "学生专区",
        footerPricing: "价格",
        footerRes: "资源",
        footerVocab: "词汇表",
        footerSheets: "练习题",
        footerContact: "联系我们",
        footerDesc: "用自适应技术赋能全球英语学习者。",
    },
    ja: {
        pageTitle: "Linguamis - 言語学習がこれまで以上に簡単に！",
        navGrammar: "文法",
        navSpeaking: "スピーキング",
        navReading: "リーディング",
        navQuiz: "クイズ",
        navWriting: "ライティング",
        navPersonas: "ペルソナ",
        navLogin: "ログイン",
        menuBtn: "メニュー",
        heroTitle: "語学力を向上させよう。無料です！",
        heroSubtitle: "パーソナライズされた読解、会話、文法の練習。",
        heroCta: "無料登録！",
        cardSpeakTitle: "スピーキングコーチ",
        cardSpeakDesc: "リアルタイムAIフィードバックで発音を改善。",
        btnStart: "話す練習",
        cardListenTitle: "リスニングラボ",
        cardListenDesc: "様々なアクセントとディクテーションで耳を鍛える。",
        btnListen: "聴く練習",
        cardGrammarTitle: "文法ガイド",
        cardGrammarDesc: "明確な説明でルールをマスター。",
        btnGrammar: "文法を学ぶ",
        cardWriteTitle: "ライティングスタジオ",
        cardWriteDesc: "エッセイやメールのライティングスキルを向上。",
        btnWrite: "書く練習",
        cardVerbsTitle: "不規則動詞",
        cardVerbsDesc: "ターゲットを絞った練習で難しい動詞を克服。",
        btnVerbs: "動詞を練習",
        cardQuizTitle: "デイリークイズ",
        cardQuizDesc: "毎日新しいクイズで知識をテスト。",
        btnQuiz: "クイズを受ける",
        cardReadTitle: "読書クラブ",
        cardReadDesc: "あらゆるレベルに適した記事や物語を探索。",
        btnRead: "読む練習",
        cardPersonasTitle: "AIペルソナ",
        cardPersonasDesc: "AIキャラクターとリアルな会話を楽しむ。",
        btnPersonas: "ペルソナに会う",
        // NEW GAMES SECTION
        cardGamesTitle: "インタラクティブゲーム",
        cardGamesDesc: "楽しいパズルやチャレンジでスキルを向上させましょう。",
        btnGames: "ゲームをする",
        // END NEW GAMES SECTION
        footerStart: "始める",
        footerAbout: "私たちについて",
        footerHow: "仕組み",
        footerStudents: "学生向け",
        footerPricing: "価格",
        footerRes: "リソース",
        footerVocab: "単語リスト",
        footerSheets: "ワークシート",
        footerContact: "お問い合わせ",
        footerDesc: "適応技術で世界中の英語学習者を支援。",
    },
    ko: {
        pageTitle: "Linguamis - 언어; 그 어느 때보다 쉽게!",
        navGrammar: "문법",
        navSpeaking: "말하기",
        navReading: "읽기",
        navQuiz: "퀴즈",
        navWriting: "쓰기",
        navPersonas: "페르소나",
        navLogin: "로그인",
        menuBtn: "메뉴",
        heroTitle: "언어 실력을 향상시키세요. 무료입니다!",
        heroSubtitle: "맞춤형 읽기, 말하기 및 문법 연습.",
        heroCta: "무료 가입!",
        cardSpeakTitle: "말하기 코치",
        cardSpeakDesc: "실시간 AI 피드백으로 발음을 개선하세요.",
        btnStart: "말하기 시작",
        cardListenTitle: "듣기 연구소",
        cardListenDesc: "다양한 억양과 받아쓰기로 귀를 훈련하세요.",
        btnListen: "듣기 시작",
        cardGrammarTitle: "문법 가이드",
        cardGrammarDesc: "명확한 설명으로 규칙을 마스터하세요.",
        btnGrammar: "문법 배우기",
        cardWriteTitle: "쓰기 스튜디오",
        cardWriteDesc: "에세이와 이메일 작문 실력을 높이세요.",
        btnWrite: "쓰기 시작",
        cardVerbsTitle: "불규칙 동사",
        cardVerbsDesc: "집중 연습으로 까다로운 동사를 정복하세요.",
        btnVerbs: "동사 연습",
        cardQuizTitle: "일일 퀴즈",
        cardQuizDesc: "매일 새로운 퀴즈로 지식을 테스트하세요.",
        btnQuiz: "퀴즈 풀기",
        cardReadTitle: "독서 클럽",
        cardReadDesc: "모든 레벨에 맞는 흥미로운 기사와 이야기를 탐색하세요.",
        btnRead: "읽기 시작",
        cardPersonasTitle: "AI 페르소나",
        cardPersonasDesc: "다양한 AI 캐릭터와 현실적인 대화를 나누세요.",
        btnPersonas: "페르소나 만나기",
        // NEW GAMES SECTION
        cardGamesTitle: "대화형 게임",
        cardGamesDesc: "재미있는 퍼즐과 도전으로 실력을 키우세요.",
        btnGames: "게임 하기",
        // END NEW GAMES SECTION
        footerStart: "시작하기",
        footerAbout: "회사 소개",
        footerHow: "작동 원리",
        footerStudents: "학생용",
        footerPricing: "가격",
        footerRes: "자료",
        footerVocab: "단어장",
        footerSheets: "학습지",
        footerContact: "문의하기",
        footerDesc: "적응형 기술로 전 세계 영어 학습자를 지원합니다.",
    },
    hi: {
        pageTitle: "Linguamis - भाषाएं; अब पहले से आसान!",
        navGrammar: "व्याकरण",
        navSpeaking: "बोलना",
        navReading: "पढ़ना",
        navQuiz: "क्विज़",
        navWriting: "लिखना",
        navPersonas: "पात्र",
        navLogin: "लॉग इन",
        menuBtn: "मेन्यू",
        heroTitle: "अपनी भाषा कौशल सुधारें। यह मुफ़्त है!",
        heroSubtitle: "व्यक्तिगत पढ़ने, बोलने और व्याकरण के अभ्यास।",
        heroCta: "मुफ़्त साइन अप करें!",
        cardSpeakTitle: "स्पीकिंग कोच",
        cardSpeakDesc: "रीयल-टाइम AI फीडबैक के साथ उच्चारण सुधारें।",
        btnStart: "बोलना शुरू करें",
        cardListenTitle: "लिस्निंग लैब",
        cardListenDesc: "विभिन्न लहजों के साथ अपने कानों को प्रशिक्षित करें।",
        btnListen: "सुनना शुरू करें",
        cardGrammarTitle: "व्याकरण गाइड",
        cardGrammarDesc: "स्पष्ट स्पष्टीकरण के साथ नियमों में महारत हासिल करें।",
        btnGrammar: "व्याकरण सीखें",
        cardWriteTitle: "राइटिंग स्टूडियो",
        cardWriteDesc: "निबंध और ईमेल के लिए अपने लेखन कौशल को बढ़ाएं।",
        btnWrite: "लिखना शुरू करें",
        cardVerbsTitle: "अनियमित क्रियाएं",
        cardVerbsDesc: "कठिन क्रियाओं को अभ्यास के साथ जीतें।",
        btnVerbs: "क्रिया अभ्यास",
        cardQuizTitle: "दैनिक क्विज़",
        cardQuizDesc: "अपने ज्ञान का परीक्षण करने के लिए हर दिन एक नई क्विज़ लें।",
        btnQuiz: "क्विज़ लें",
        cardReadTitle: "रीडिंग क्लब",
        cardReadDesc: "सभी स्तरों के लिए दिलचस्प लेख और कहानियां पढ़ें।",
        btnRead: "पढ़ना शुरू करें",
        cardPersonasTitle: "AI पात्र",
        cardPersonasDesc: "AI पात्रों के साथ यथार्थवादी बातचीत करें।",
        btnPersonas: "पात्रों से मिलें",
        // NEW GAMES SECTION
        cardGamesTitle: "इंटरैक्टिव खेल",
        cardGamesDesc: "मजेदार पहेलियों और चुनौतियों के साथ अपने कौशल को बढ़ाएं।",
        btnGames: "खेल खेलें",
        // END NEW GAMES SECTION
        footerStart: "शुरू करें",
        footerAbout: "हमारे बारे में",
        footerHow: "यह कैसे काम करता है",
        footerStudents: "छात्रों के लिए",
        footerPricing: "मूल्य निर्धारण",
        footerRes: "संसाधन",
        footerVocab: "शब्दावली सूची",
        footerSheets: "वर्कशीट",
        footerContact: "संपर्क करें",
        footerDesc: "अनुकूली तकनीक के साथ दुनिया भर के शिक्षार्थियों को सशक्त बनाना।",
    },
    pt: {
        pageTitle: "Linguamis - Línguas; Mais fácil do que nunca!",
        navGrammar: "Gramática",
        navSpeaking: "Falar",
        navReading: "Ler",
        navQuiz: "Quiz",
        navWriting: "Escrever",
        navPersonas: "Personas",
        navLogin: "Entrar",
        menuBtn: "Menu",
        heroTitle: "Melhore suas habilidades linguísticas. É grátis!",
        heroSubtitle: "Exercícios personalizados de leitura, fala e gramática.",
        heroCta: "Cadastre-se GRÁTIS!",
        cardSpeakTitle: "Treinador de Fala",
        cardSpeakDesc: "Melhore a pronúncia com feedback de IA em tempo real.",
        btnStart: "Começar a Falar",
        cardListenTitle: "Lab de Escuta",
        cardListenDesc: "Treine seu ouvido com sotaques diversos e ditados.",
        btnListen: "Começar a Ouvir",
        cardGrammarTitle: "Guia de Gramática",
        cardGrammarDesc: "Domine as regras com explicações claras.",
        btnGrammar: "Aprender Gramática",
        cardWriteTitle: "Estúdio de Escrita",
        cardWriteDesc: "Melhore suas habilidades de escrita para redações e e-mails.",
        btnWrite: "Começar a Escrever",
        cardVerbsTitle: "Verbos Irregulares",
        cardVerbsDesc: "Conquiste verbos difíceis com prática direcionada.",
        btnVerbs: "Praticar Verbos",
        cardQuizTitle: "Quiz Diário",
        cardQuizDesc: "Desafie-se com um novo quiz todos os dias.",
        btnQuiz: "Fazer Quiz",
        cardReadTitle: "Clube de Leitura",
        cardReadDesc: "Explore artigos e histórias para todos os níveis.",
        btnRead: "Começar a Ler",
        cardPersonasTitle: "Personas IA",
        cardPersonasDesc: "Participe de conversas realistas com personagens de IA.",
        btnPersonas: "Conhecer Personas",
        // NEW GAMES SECTION
        cardGamesTitle: "Jogos Interativos",
        cardGamesDesc: "Melhore suas habilidades com quebra-cabeças e desafios divertidos.",
        btnGames: "Jogar",
        // END NEW GAMES SECTION
        footerStart: "Começar",
        footerAbout: "Sobre Nós",
        footerHow: "Como funciona",
        footerStudents: "Para Estudantes",
        footerPricing: "Preços",
        footerRes: "Recursos",
        footerVocab: "Listas de Vocabulário",
        footerSheets: "Planilhas",
        footerContact: "Contato",
        footerDesc: "Capacitando estudantes de inglês em todo o mundo.",
    },
    pl: {
        pageTitle: "Linguamis - Języki; Łatwiej niż kiedykolwiek!",
        navGrammar: "Gramatyka",
        navSpeaking: "Mówienie",
        navReading: "Czytanie",
        navQuiz: "Quiz",
        navWriting: "Pisanie",
        navPersonas: "Persony",
        navLogin: "Zaloguj",
        menuBtn: "Menu",
        heroTitle: "Popraw swoje umiejętności językowe. Za darmo!",
        heroSubtitle: "Spersonalizowane ćwiczenia z czytania, mówienia i gramatyki.",
        heroCta: "Zarejestruj się ZA DARMO!",
        cardSpeakTitle: "Trener Mowy",
        cardSpeakDesc: "Popraw wymowę dzięki informacjom zwrotnym AI w czasie rzeczywistym.",
        btnStart: "Zacznij Mówić",
        cardListenTitle: "Lab Słuchania",
        cardListenDesc: "Trenuj słuch dzięki różnorodnym akcentom i dyktandom.",
        btnListen: "Zacznij Słuchać",
        cardGrammarTitle: "Przewodnik Gramatyczny",
        cardGrammarDesc: "Opanuj zasady dzięki jasnym wyjaśnieniom.",
        btnGrammar: "Ucz się Gramatyki",
        cardWriteTitle: "Studio Pisania",
        cardWriteDesc: "Popraw swoje umiejętności pisania esejów i e-maili.",
        btnWrite: "Zacznij Pisać",
        cardVerbsTitle: "Czasowniki Nieregularne",
        cardVerbsDesc: "Opanuj trudne czasowniki dzięki ukierunkowanym ćwiczeniom.",
        btnVerbs: "Ćwicz Czasowniki",
        cardQuizTitle: "Codzienny Quiz",
        cardQuizDesc: "Sprawdzaj swoją wiedzę codziennie nowym quizem.",
        btnQuiz: "Rozwiąż Quiz",
        cardReadTitle: "Klub Czytelnika",
        cardReadDesc: "Odkrywaj ciekawe artykuły i historie dla każdego poziomu.",
        btnRead: "Zacznij Czytać",
        cardPersonasTitle: "Persony AI",
        cardPersonasDesc: "Angażuj się w realistyczne rozmowy z postaciami AI.",
        btnPersonas: "Poznaj Persony",
        // NEW GAMES SECTION
        cardGamesTitle: "Gry Interaktywne",
        cardGamesDesc: "Popraw swoje umiejętności dzięki zabawnym łamigłówkom i wyzwaniom.",
        btnGames: "Graj",
        // END NEW GAMES SECTION
        footerStart: "Zacznij",
        footerAbout: "O nas",
        footerHow: "Jak to działa",
        footerStudents: "Dla Uczniów",
        footerPricing: "Cennik",
        footerRes: "Zasoby",
        footerVocab: "Listy Słówek",
        footerSheets: "Arkusze",
        footerContact: "Kontakt",
        footerDesc: "Wspieranie osób uczących się angielskiego na całym świecie.",
    },
    nl: {
        pageTitle: "Linguamis - Talen; Makkelijker dan ooit!",
        navGrammar: "Grammatica",
        navSpeaking: "Spreken",
        navReading: "Lezen",
        navQuiz: "Quiz",
        navWriting: "Schrijven",
        navPersonas: "Persona's",
        navLogin: "Inloggen",
        menuBtn: "Menu",
        heroTitle: "Verbeter je taalvaardigheid. Het is gratis!",
        heroSubtitle: "Gepersonaliseerde lees-, spreek- en grammatica-oefeningen.",
        heroCta: "GRATIS Aanmelden!",
        cardSpeakTitle: "Spreekcoach",
        cardSpeakDesc: "Verbeter uitspraak met real-time AI-feedback.",
        btnStart: "Start Spreken",
        cardListenTitle: "Luisterlab",
        cardListenDesc: "Train je gehoor met diverse accenten en dictees.",
        btnListen: "Start Luisteren",
        cardGrammarTitle: "Grammaticagids",
        cardGrammarDesc: "Beheers regels met duidelijke uitleg.",
        btnGrammar: "Leer Grammatica",
        cardWriteTitle: "Schrijfstudio",
        cardWriteDesc: "Verbeter je schrijfvaardigheid voor essays en e-mails.",
        btnWrite: "Start Schrijven",
        cardVerbsTitle: "Onregelmatige Werkwoorden",
        cardVerbsDesc: "Verover lastige werkwoorden met gerichte oefening.",
        btnVerbs: "Oefen Werkwoorden",
        cardQuizTitle: "Dagelijkse Quiz",
        cardQuizDesc: "Daag jezelf elke dag uit met een nieuwe quiz.",
        btnQuiz: "Doe de Quiz",
        cardReadTitle: "Leesclub",
        cardReadDesc: "Verken interessante artikelen voor alle niveaus.",
        btnRead: "Start Lezen",
        cardPersonasTitle: "AI Persona's",
        cardPersonasDesc: "Voer realistische gesprekken met AI-personages.",
        btnPersonas: "Ontmoet Persona's",
        // NEW GAMES SECTION
        cardGamesTitle: "Interactieve Spellen",
        cardGamesDesc: "Verbeter je vaardigheden met leuke puzzels en uitdagingen.",
        btnGames: "Speel Spellen",
        // END NEW GAMES SECTION
        footerStart: "Beginnen",
        footerAbout: "Over Ons",
        footerHow: "Hoe het werkt",
        footerStudents: "Voor Studenten",
        footerPricing: "Prijzen",
        footerRes: "Bronnen",
        footerVocab: "Woordenlijsten",
        footerSheets: "Werkbladen",
        footerContact: "Contact",
        footerDesc: "Engelse leerlingen wereldwijd versterken met adaptieve technologie.",
    },
    id: {
        pageTitle: "Linguamis - Bahasa; Lebih Mudah dari Sebelumnya!",
        navGrammar: "Tata Bahasa",
        navSpeaking: "Berbicara",
        navReading: "Membaca",
        navQuiz: "Kuis",
        navWriting: "Menulis",
        navPersonas: "Persona",
        navLogin: "Masuk",
        menuBtn: "Menu",
        heroTitle: "Tingkatkan kemampuan bahasa Anda. Gratis!",
        heroSubtitle: "Latihan membaca, berbicara, dan tata bahasa yang dipersonalisasi.",
        heroCta: "Daftar GRATIS!",
        cardSpeakTitle: "Pelatih Bicara",
        cardSpeakDesc: "Tingkatkan pengucapan dengan umpan balik AI waktu nyata.",
        btnStart: "Mulai Bicara",
        cardListenTitle: "Lab Mendengar",
        cardListenDesc: "Latih telinga Anda dengan beragam aksen.",
        btnListen: "Mulai Mendengar",
        cardGrammarTitle: "Panduan Tata Bahasa",
        cardGrammarDesc: "Kuasai aturan dengan penjelasan yang jelas.",
        btnGrammar: "Belajar Tata Bahasa",
        cardWriteTitle: "Studio Menulis",
        cardWriteDesc: "Tingkatkan keterampilan menulis esai dan email.",
        btnWrite: "Mulai Menulis",
        cardVerbsTitle: "Kata Kerja Tak Beraturan",
        cardVerbsDesc: "Taklukkan kata kerja sulit dengan latihan.",
        btnVerbs: "Latihan Kata Kerja",
        cardQuizTitle: "Kuis Harian",
        cardQuizDesc: "Tantang diri Anda dengan kuis baru setiap hari.",
        btnQuiz: "Ikuti Kuis",
        cardReadTitle: "Klub Membaca",
        cardReadDesc: "Jelajahi artikel dan cerita menarik untuk semua level.",
        btnRead: "Mulai Membaca",
        cardPersonasTitle: "Persona AI",
        cardPersonasDesc: "Terlibat dalam percakapan realistis dengan karakter AI.",
        btnPersonas: "Temui Persona",
        // NEW GAMES SECTION
        cardGamesTitle: "Permainan Interaktif",
        cardGamesDesc: "Tingkatkan keterampilan Anda dengan teka-teki dan tantangan seru.",
        btnGames: "Main Game",
        // END NEW GAMES SECTION
        footerStart: "Mulai",
        footerAbout: "Tentang Kami",
        footerHow: "Cara kerja",
        footerStudents: "Untuk Siswa",
        footerPricing: "Harga",
        footerRes: "Sumber Daya",
        footerVocab: "Daftar Kosakata",
        footerSheets: "Lembar Kerja",
        footerContact: "Hubungi Kami",
        footerDesc: "Memberdayakan pelajar bahasa Inggris di seluruh dunia.",
    },
    vi: {
        pageTitle: "Linguamis - Ngôn ngữ; Dễ dàng hơn bao giờ hết!",
        navGrammar: "Ngữ pháp",
        navSpeaking: "Nói",
        navReading: "Đọc",
        navQuiz: "Trắc nghiệm",
        navWriting: "Viết",
        navPersonas: "Nhân vật",
        navLogin: "Đăng nhập",
        menuBtn: "Menu",
        heroTitle: "Cải thiện kỹ năng ngôn ngữ. Hoàn toàn miễn phí!",
        heroSubtitle: "Các bài tập đọc, nói và ngữ pháp được cá nhân hóa.",
        heroCta: "Đăng ký MIỄN PHÍ!",
        cardSpeakTitle: "Huấn luyện viên Nói",
        cardSpeakDesc: "Cải thiện phát âm với phản hồi AI thời gian thực.",
        btnStart: "Bắt đầu Nói",
        cardListenTitle: "Phòng nghe",
        cardListenDesc: "Luyện tai nghe với nhiều giọng và bài chính tả.",
        btnListen: "Bắt đầu Nghe",
        cardGrammarTitle: "Hướng dẫn Ngữ pháp",
        cardGrammarDesc: "Nắm vững các quy tắc với giải thích rõ ràng.",
        btnGrammar: "Học Ngữ pháp",
        cardWriteTitle: "Phòng Viết",
        cardWriteDesc: "Nâng cao kỹ năng viết luận và email.",
        btnWrite: "Bắt đầu Viết",
        cardVerbsTitle: "Động từ Bất quy tắc",
        cardVerbsDesc: "Chinh phục các động từ khó với bài tập mục tiêu.",
        btnVerbs: "Luyện Động từ",
        cardQuizTitle: "Trắc nghiệm Hằng ngày",
        cardQuizDesc: "Thử thách bản thân với bài trắc nghiệm mới mỗi ngày.",
        btnQuiz: "Làm Trắc nghiệm",
        cardReadTitle: "Câu lạc bộ Đọc",
        cardReadDesc: "Khám phá các bài báo và câu chuyện thú vị.",
        btnRead: "Bắt đầu Đọc",
        cardPersonasTitle: "Nhân vật AI",
        cardPersonasDesc: "Tham gia trò chuyện thực tế với các nhân vật AI.",
        btnPersonas: "Gặp gỡ Nhân vật",
        // NEW GAMES SECTION
        cardGamesTitle: "Trò chơi Tương tác",
        cardGamesDesc: "Cải thiện kỹ năng với các câu đố và thử thách thú vị.",
        btnGames: "Chơi Game",
        // END NEW GAMES SECTION
        footerStart: "Bắt đầu",
        footerAbout: "Về chúng tôi",
        footerHow: "Cách hoạt động",
        footerStudents: "Cho Học sinh",
        footerPricing: "Giá cả",
        footerRes: "Tài nguyên",
        footerVocab: "Danh sách từ vựng",
        footerSheets: "Bài tập",
        footerContact: "Liên hệ",
        footerDesc: "Trao quyền cho người học tiếng Anh trên toàn thế giới.",
    },
    th: {
        pageTitle: "Linguamis - ภาษา; ง่ายกว่าที่เคย!",
        navGrammar: "ไวยากรณ์",
        navSpeaking: "การพูด",
        navReading: "การอ่าน",
        navQuiz: "แบบทดสอบ",
        navWriting: "การเขียน",
        navPersonas: "ตัวละคร",
        navLogin: "เข้าสู่ระบบ",
        menuBtn: "เมนู",
        heroTitle: "พัฒนาทักษะภาษาของคุณ ฟรี!",
        heroSubtitle: "แบบฝึกหัดการอ่าน การพูด และไวยากรณ์ส่วนบุคคล",
        heroCta: "สมัครฟรี!",
        cardSpeakTitle: "โค้ชการพูด",
        cardSpeakDesc: "ปรับปรุงการออกเสียงด้วยคำติชม AI แบบเรียลไทม์",
        btnStart: "เริ่มพูด",
        cardListenTitle: "ห้องแล็บการฟัง",
        cardListenDesc: "ฝึกหูของคุณด้วยสำเนียงต่างๆ",
        btnListen: "เริ่มฟัง",
        cardGrammarTitle: "คู่มือไวยากรณ์",
        cardGrammarDesc: "เข้าใจกฎต่างๆ ด้วยคำอธิบายที่ชัดเจน",
        btnGrammar: "เรียนไวยากรณ์",
        cardWriteTitle: "สตูดิโอการเขียน",
        cardWriteDesc: "เพิ่มทักษะการเขียนเรียงความและอีเมล",
        btnWrite: "เริ่มเขียน",
        cardVerbsTitle: "กริยาผิดปกติ",
        cardVerbsDesc: "พิชิตคำกริยายากๆ ด้วยการฝึกฝน",
        btnVerbs: "ฝึกคำกริยา",
        cardQuizTitle: "แบบทดสอบรายวัน",
        cardQuizDesc: "ท้าทายตัวเองด้วยแบบทดสอบใหม่ทุกวัน",
        btnQuiz: "ทำแบบทดสอบ",
        cardReadTitle: "ชมรมการอ่าน",
        cardReadDesc: "สำรวจบทความและเรื่องราวที่น่าสนใจ",
        btnRead: "เริ่มอ่าน",
        cardPersonasTitle: "ตัวละคร AI",
        cardPersonasDesc: "มีส่วนร่วมในการสนทนาที่สมจริงกับตัวละคร AI",
        btnPersonas: "พบกับตัวละคร",
        // NEW GAMES SECTION
        cardGamesTitle: "เกมแบบโต้ตอบ",
        cardGamesDesc: "เพิ่มทักษะของคุณด้วยปริศนาและความท้าทายที่สนุกสนาน",
        btnGames: "เล่นเกม",
        // END NEW GAMES SECTION
        footerStart: "เริ่มต้น",
        footerAbout: "เกี่ยวกับเรา",
        footerHow: "ทำงานอย่างไร",
        footerStudents: "สำหรับนักเรียน",
        footerPricing: "ราคา",
        footerRes: "ทรัพยากร",
        footerVocab: "รายการคำศัพท์",
        footerSheets: "ใบงาน",
        footerContact: "ติดต่อเรา",
        footerDesc: "เสริมสร้างศักยภาพผู้เรียนภาษาอังกฤษทั่วโลก",
    },
    el: {
        pageTitle: "Linguamis - Γλώσσες; Πιο εύκολα από ποτέ!",
        navGrammar: "Γραμματική",
        navSpeaking: "Ομιλία",
        navReading: "Ανάγνωση",
        navQuiz: "Κουίζ",
        navWriting: "Γραφή",
        navPersonas: "Πρόσωπα",
        navLogin: "Σύνδεση",
        menuBtn: "Μενού",
        heroTitle: "Βελτιώστε τις γλωσσικές σας δεξιότητες. Δωρεάν!",
        heroSubtitle: "Εξατομικευμένες ασκήσεις ανάγνωσης, ομιλίας και γραμματικής.",
        heroCta: "Εγγραφείτε ΔΩΡΕΑΝ!",
        cardSpeakTitle: "Προπονητής Ομιλίας",
        cardSpeakDesc: "Βελτιώστε την προφορά με σχόλια AI σε πραγματικό χρόνο.",
        btnStart: "Έναρξη Ομιλίας",
        cardListenTitle: "Εργαστήριο Ακοής",
        cardListenDesc: "Εκπαιδεύστε το αυτί σας με διάφορες προφορές.",
        btnListen: "Έναρξη Ακρόασης",
        cardGrammarTitle: "Οδηγός Γραμματικής",
        cardGrammarDesc: "Κατακτήστε τους κανόνες με σαφείς εξηγήσεις.",
        btnGrammar: "Μάθετε Γραμματική",
        cardWriteTitle: "Στούντιο Γραφής",
        cardWriteDesc: "Βελτιώστε τις δεξιότητες γραφής για δοκίμια και email.",
        btnWrite: "Έναρξη Γραφής",
        cardVerbsTitle: "Ανώμαλα Ρήματα",
        cardVerbsDesc: "Κατακτήστε δύσκολα ρήματα με στοχευμένη εξάσκηση.",
        btnVerbs: "Εξάσκηση Ρημάτων",
        cardQuizTitle: "Καθημερινό Κουίζ",
        cardQuizDesc: "Δοκιμάστε τις γνώσεις σας με ένα νέο κουίζ κάθε μέρα.",
        btnQuiz: "Κάντε Κουίζ",
        cardReadTitle: "Λέσχη Ανάγνωσης",
        cardReadDesc: "Εξερευνήστε ενδιαφέροντα άρθρα και ιστορίες.",
        btnRead: "Έναρξη Ανάγνωσης",
        cardPersonasTitle: "AI Πρόσωπα",
        cardPersonasDesc: "Συμμετάσχετε σε ρεαλιστικές συνομιλίες με χαρακτήρες AI.",
        btnPersonas: "Γνωρίστε Πρόσωπα",
        // NEW GAMES SECTION
        cardGamesTitle: "Διαδραστικά Παιχνίδια",
        cardGamesDesc: "Βελτιώστε τις δεξιότητές σας με διασκεδαστικά παζλ και προκλήσεις.",
        btnGames: "Παίξτε",
        // END NEW GAMES SECTION
        footerStart: "Ξεκινήστε",
        footerAbout: "Σχετικά με εμάς",
        footerHow: "Πώς λειτουργεί",
        footerStudents: "Για Μαθητές",
        footerPricing: "Τιμολόγηση",
        footerRes: "Πόροι",
        footerVocab: "Λίστες Λεξιλογίου",
        footerSheets: "Φύλλα εργασίας",
        footerContact: "Επικοινωνία",
        footerDesc: "Ενδυνάμωση των μαθητών αγγλικής γλώσσας παγκοσμίως.",
    },
    cs: {
        pageTitle: "Linguamis - Jazyky; Jednodušší než kdy dřív!",
        navGrammar: "Gramatika",
        navSpeaking: "Mluvení",
        navReading: "Čtení",
        navQuiz: "Kvíz",
        navWriting: "Psaní",
        navPersonas: "Persony",
        navLogin: "Přihlásit",
        menuBtn: "Menu",
        heroTitle: "Zlepšete své jazykové dovednosti. Zdarma!",
        heroSubtitle: "Personalizovaná cvičení čtení, mluvení a gramatiky.",
        heroCta: "Zaregistrujte se ZDARMA!",
        cardSpeakTitle: "Trenér Mluvení",
        cardSpeakDesc: "Zlepšete výslovnost pomocí zpětné vazby AI v reálném čase.",
        btnStart: "Začít Mluvit",
        cardListenTitle: "Laboratoř Poslechu",
        cardListenDesc: "Trénujte uši s různými přízvuky a diktáty.",
        btnListen: "Začít Poslouchat",
        cardGrammarTitle: "Průvodce Gramatikou",
        cardGrammarDesc: "Ovládněte pravidla díky jasným vysvětlením.",
        btnGrammar: "Učit se Gramatiku",
        cardWriteTitle: "Studio Psaní",
        cardWriteDesc: "Zlepšete své dovednosti psaní esejů a e-mailů.",
        btnWrite: "Začít Psát",
        cardVerbsTitle: "Nepravidelná Slovesa",
        cardVerbsDesc: "Zvládněte obtížná slovesa cíleným procvičováním.",
        btnVerbs: "Procvičit Slovesa",
        cardQuizTitle: "Denní Kvíz",
        cardQuizDesc: "Otestujte své znalosti každý den novým kvízem.",
        btnQuiz: "Spustit Kvíz",
        cardReadTitle: "Čtenářský Klub",
        cardReadDesc: "Prozkoumejte zajímavé články a příběhy.",
        btnRead: "Začít Číst",
        cardPersonasTitle: "AI Persony",
        cardPersonasDesc: "Zapojte se do realistických konverzací s AI postavami.",
        btnPersonas: "Poznat Persony",
        // NEW GAMES SECTION
        cardGamesTitle: "Interaktivní Hry",
        cardGamesDesc: "Zlepšete své dovednosti pomocí zábavných hádanek a výzev.",
        btnGames: "Hrát Hry",
        // END NEW GAMES SECTION
        footerStart: "Začít",
        footerAbout: "O nás",
        footerHow: "Jak to funguje",
        footerStudents: "Pro Studenty",
        footerPricing: "Ceník",
        footerRes: "Zdroje",
        footerVocab: "Slovníčky",
        footerSheets: "Pracovní listy",
        footerContact: "Kontakt",
        footerDesc: "Posílení studentů angličtiny po celém světě.",
    }
};

// --- MAIN FUNCTION 1: TRIGGERED BY USER DROPDOWN ---
function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);
    location.reload(); 
}

// --- MAIN FUNCTION 2: RUNS AUTOMATICALLY ON PAGE LOAD ---
function applyLanguage(lang) {
    if (lang === 'ar') {
        document.documentElement.setAttribute('dir', 'rtl');
        document.documentElement.setAttribute('lang', 'ar');
    } else {
        document.documentElement.setAttribute('dir', 'ltr');
        document.documentElement.setAttribute('lang', lang);
    }

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });

    const mainSelect = document.getElementById('languageSelect');
    if (mainSelect) mainSelect.value = lang;
    
    const mobileSelect = document.getElementById('mobileLangSelect');
    if (mobileSelect) mobileSelect.value = lang;
}

// --- BOOT UP SEQUENCE ---
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'en';
    applyLanguage(savedLang);
});
